namespace Renewly.Domain.Common;

/// <summary>
/// Base type for all persisted entities. Ids are generated by EF Core
/// (sequential GUIDs on SQL Server) unless explicitly assigned, e.g. for seed data.
/// </summary>
public abstract class BaseEntity
{
    public Guid Id { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }
}

/// <summary>
/// Entities that are hidden rather than physically removed. A global query filter excludes them.
/// </summary>
public interface ISoftDeletable
{
    bool IsDeleted { get; set; }

    DateTime? DeletedAtUtc { get; set; }
}
